---
- name: Configure webserverr
  hosts: all
  become: yes
  remote_user: ubuntu


  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: present

    - name: default index file
      template: 
        src: index.html
        dest: /var/www/html/index.html
        

    - name: download cloudwatch
      ansible.builtin.get_url: 
        url: https://amazoncloudwatch-agent.s3.amazonaws.com/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
        dest: ~/amazon-cloudwatch-agent.deb

    - name: Install CloudWatch Agent
      shell: cd ~/ && sudo dpkg -i -E ./amazon-cloudwatch-agent.deb

    - name: Template cloudwatch config
      template: 
        src: cloudwatch-agent.config.json
        dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json

    - name: create collectd dir
      file:
        path: /usr/share/collectd/
        state: directory

    - name: create collectd types.db
      file:
        path: /usr/share/collectd/types.db
        state: touch

    - name: Starting cwagent
      shell: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json