name: Deploy infrastructure on AWS
run-name: ${{ github.actor }} is deploying infraestrutucture
on: [push]

    

jobs:
    deploy_infra:
        runs-on: ubuntu-latest
        env:
          TF_VAR_SSH_PUB_KEY: ${{ secrets.SSH_PUB_KEY }}
        steps:

          - name: Configure AWS Credentials
            id: aws_credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
                aws-region: "us-east-1"
                aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
                aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        
          - name: Checkout to repository
            uses: actions/checkout@v4

          - uses: hashicorp/setup-terraform@v3

          - name: configure aws resources
            run: cd infra && terraform init && terraform apply -auto-approve
            
            

          - name: retrieve public ip of ec2_instance
            run: cd infra && echo ip=$(terraform output -raw ec2_public_ip) >> $GITHUB_ENV
            id: ec2_ip_out
            
          - name: configure inventorio
            run: sed "s/<EC2_IP>$/${{ env.ip }}/g" config/inventory.ini -i

          - name: install ansible
            run: sudo apt update && sudo apt install ansible -y

          - name: configure ssh key
            run: echo "${{ secrets.SSH_KEY }}" >> ~/ssh_key && chmod 600 ~/ssh_key

          - name: execute ansible playbook
            run: cd config && ansible-playbook -i inventory.ini main.yml
            env:
                ANSIBLE_HOST_KEY_CHECKING: False
